# Generated by Django 2.1.7 on 2019-04-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annuaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='abadaa9518@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='numero',
            field=models.CharField(default='773012470', max_length=10),
        ),
    ]
